format_version: 3
pipelines:
  docker-golang-dojo:
    group: go
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        blacklist:
          - "**/*.gocd.yaml"
          - "**/*.md"
    secure_variables:
      VAULT_TOKEN: "AES:foEaAO3PeRHqhEEzJTmqDQ==:EgoBiIVNhLc/SR4gM2BSvBpPfXoy1NvCfrr68q2Wd/Tk39QdmReQQMpTBACHazdd"
    stages:
      - build:
          clean_workspace: true
          jobs:
            docker_image:
              elastic_profile_id: w.c1.m1024.e5
              artifacts:
                - build:
                    source: image/imagerc
                    destination:
              tasks:
               - exec:
                  command: /bin/bash
                  arguments:
                    - -c
                    - ./tasks build
      - itest:
          clean_workspace: true
          jobs:
            end_user:
              elastic_profile_id: w.c1.m1024.e5
              tasks:
                - fetch:
                    stage: build
                    job: docker_image
                    is_file: yes
                    source: imagerc
                    destination: image/
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks itest
      - release:
          clean_workspace: true
          jobs:
            code:
              elastic_profile_id: w.c1.m1024.e5
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks release
      - publish:
          clean_workspace: true
          jobs:
            docker_image:
              elastic_profile_id: w.c1.m1024.e5
              tasks:
                - fetch:
                    stage: build
                    job: docker_image
                    is_file: yes
                    source: imagerc
                    destination: image/
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks publish
