#!/bin/bash

set -e
if [[ ! -f ./releaser ]];then
  wget --quiet http://http.archive.ai-traders.com/releaser/1.0.3/releaser
fi
source ./releaser
if [[ ! -f ./docker-ops ]];then
  wget --quiet http://http.archive.ai-traders.com/docker-ops/0.2.3/docker-ops
fi
source ./docker-ops
# This goes as last in order to let end user variables override default values
releaser_init

image_name="docker-registry.ai-traders.com/golang-ide"
image_dir="./image"
imagerc_filename="imagerc"

command="$1"
case "${command}" in
  set_version)
      if [[ -n "$2" ]]; then
        next_version="$2"
        set_next_oversion "${next_version}"
      else
        next_version=$(get_next_oversion)
      fi
      set_version_in_changelog "${changelog_file}" "${next_version}"
      exit $?
      ;;
  verify_version)
      version_from_changelog=$(get_last_version_from_changelog "${changelog_file}")
      if git tag | grep "${version_from_changelog}"; then
        log_error "The last version from changelog was already git tagged: ${version_from_changelog}"
        exit 1
      fi
      exit $?
      ;;
  build)
      image_name_no_registry="${image_name/docker-registry.ai-traders.com\//}"
      production_image_tag=$(get_last_version_from_changelog "${changelog_file}")
      docker_build_options="--build-arg this_image_name_arg=${image_name_no_registry} --build-arg this_image_tag_arg=${production_image_tag}"
      docker_build "./image" "imagerc" "${image_name}" "$2"
      exit $?
      ;;
  itest)
      source_imagerc "${image_dir}"  "${imagerc_filename}"
      echo "Testing image: ${AIT_DOCKER_IMAGE_NAME}:${AIT_DOCKER_IMAGE_TAG}"
      # use the production ENTRYPOINT
      echo "DOJO_DOCKER_IMAGE=\"${AIT_DOCKER_IMAGE_NAME}:${AIT_DOCKER_IMAGE_TAG}\"" > Dojofile.to_be_tested
      echo "DOJO_IDENTITY_OUTER=\"$(pwd)/test/integration/identities/full\"" >> Dojofile.to_be_tested
      echo "DOJO_WORK_OUTER=$(pwd)/test/integration/test_dojo_work" >> Dojofile.to_be_tested
      echo "DOJO_WORK_INNER=\"/dojo/work/src/github.com/notexistentuser/myproject\"" >> Dojofile.to_be_tested
      echo "DOJO_DOCKER_OPTIONS=\" -v /run/docker.sock:/run/docker.sock\"" >> Dojofile.to_be_tested

      echo "DOJO_DOCKER_IMAGE=\"${AIT_DOCKER_IMAGE_NAME}:${AIT_DOCKER_IMAGE_TAG}\"" > Dojofile.to_be_tested_multiproj
      echo "DOJO_IDENTITY_OUTER=\"$(pwd)/test/integration/identities/full\"" >> Dojofile.to_be_tested_multiproj
      # different test dojo_work
      echo "DOJO_WORK_OUTER=$(pwd)/test/integration/test_dojo_work_multiproj" >> Dojofile.to_be_tested_multiproj
      # no DOJO_WORK_INNER, defaults to /dojo/work
      time bats "$(pwd)/test/integration/end_user/bats"
      exit $?
      ;;
  example)
      last_tag=$(get_last_git_tagged_version)
      echo "DOJO_DOCKER_IMAGE=\"${image_name}:${last_tag}\"" > ./Dojofile.example
      echo "DOJO_IDENTITY_OUTER=\"$(pwd)/test/integration/identities/full\"" >> ./Dojofile.example
      echo "DOJO_WORK_OUTER=$(pwd)/test/integration/test_dojo_work" >> Dojofile.example
      echo "DOJO_DOCKER_OPTIONS=\" -v /run/docker.sock:/run/docker.sock\"" >> Dojofile.example
      exit $?
      ;;
  release)
      verify_version_for_release
      git_tag_from_oversion
      old_version=$(get_next_oversion)
      next_version=$(bump_patch_version "${old_version}")
      set_next_oversion "${next_version}"
      exit $?
      ;;
  publish)
      production_image_tag=$(get_last_version_from_changelog "${changelog_file}")
      validate_version_is_semver "${production_image_tag}"
      source_imagerc "${image_dir}"  "${imagerc_filename}"
      docker_push "${AIT_DOCKER_IMAGE_NAME}" "${AIT_DOCKER_IMAGE_TAG}" "${production_image_tag}"
      exit $?
      ;;
  *)
      echo "Invalid command: '${command}'"
      exit 1
      ;;
esac
set +e
